/*
 * This file is generated by jOOQ.
 */
package org.railwaystations.rsapi.jooq.tables


import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.railwaystations.rsapi.jooq.Test
import org.railwaystations.rsapi.jooq.keys.FK_COUNTRY
import org.railwaystations.rsapi.jooq.keys.KEY_COUNTRIES_PRIMARY
import org.railwaystations.rsapi.jooq.tables.ProviderappsTable.ProviderappsPath
import org.railwaystations.rsapi.jooq.tables.records.CountriesRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CountriesTable(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CountriesRecord>?,
    parentPath: InverseForeignKey<out Record, CountriesRecord>?,
    aliased: Table<CountriesRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CountriesRecord>(
    alias,
    Test.TEST,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>test.countries</code>
         */
        val CountriesTable: CountriesTable = CountriesTable()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CountriesRecord> = CountriesRecord::class.java

    /**
     * The column <code>test.countries.id</code>.
     */
    val id: TableField<CountriesRecord, String?> = createField(DSL.name("id"), SQLDataType.CHAR(2).nullable(false), this, "")

    /**
     * The column <code>test.countries.name</code>.
     */
    val name: TableField<CountriesRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>test.countries.timetableUrlTemplate</code>.
     */
    val timetableurltemplate: TableField<CountriesRecord, String?> = createField(DSL.name("timetableUrlTemplate"), SQLDataType.VARCHAR(1024).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>test.countries.email</code>.
     */
    val email: TableField<CountriesRecord, String?> = createField(DSL.name("email"), SQLDataType.VARCHAR(255).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>test.countries.overrideLicense</code>.
     */
    val overridelicense: TableField<CountriesRecord, String?> = createField(DSL.name("overrideLicense"), SQLDataType.VARCHAR(100).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>test.countries.active</code>.
     */
    val active: TableField<CountriesRecord, Boolean?> = createField(DSL.name("active"), SQLDataType.BIT.defaultValue(DSL.field(DSL.raw("b'1'"), SQLDataType.BIT)), this, "")

    private constructor(alias: Name, aliased: Table<CountriesRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CountriesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CountriesRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>test.countries</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>test.countries</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>test.countries</code> table reference
     */
    constructor(): this(DSL.name("countries"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CountriesRecord>?, parentPath: InverseForeignKey<out Record, CountriesRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, CountriesTable, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class CountriesPath : CountriesTable, Path<CountriesRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, CountriesRecord>?, parentPath: InverseForeignKey<out Record, CountriesRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<CountriesRecord>): super(alias, aliased)
        override fun `as`(alias: String): CountriesPath = CountriesPath(DSL.name(alias), this)
        override fun `as`(alias: Name): CountriesPath = CountriesPath(alias, this)
        override fun `as`(alias: Table<*>): CountriesPath = CountriesPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Test.TEST
    override fun getPrimaryKey(): UniqueKey<CountriesRecord> = KEY_COUNTRIES_PRIMARY

    private lateinit var _providerapps: ProviderappsPath

    /**
     * Get the implicit to-many join path to the <code>test.providerApps</code>
     * table
     */
    fun providerapps(): ProviderappsPath {
        if (!this::_providerapps.isInitialized)
            _providerapps = ProviderappsPath(this, null, FK_COUNTRY.inverseKey)

        return _providerapps;
    }

    val providerapps: ProviderappsPath
        get(): ProviderappsPath = providerapps()
    override fun `as`(alias: String): CountriesTable = CountriesTable(DSL.name(alias), this)
    override fun `as`(alias: Name): CountriesTable = CountriesTable(alias, this)
    override fun `as`(alias: Table<*>): CountriesTable = CountriesTable(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): CountriesTable = CountriesTable(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): CountriesTable = CountriesTable(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): CountriesTable = CountriesTable(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): CountriesTable = CountriesTable(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): CountriesTable = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): CountriesTable = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): CountriesTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): CountriesTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): CountriesTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): CountriesTable = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): CountriesTable = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): CountriesTable = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): CountriesTable = where(DSL.notExists(select))
}
