/*
 * This file is generated by jOOQ.
 */
package org.railwaystations.rsapi.jooq.tables


import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.railwaystations.rsapi.jooq.Test
import org.railwaystations.rsapi.jooq.keys.KEY_OAUTH2_AUTHORIZATION_CONSENT_PRIMARY
import org.railwaystations.rsapi.jooq.tables.records.Oauth2AuthorizationConsentRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Oauth2AuthorizationConsentTable(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, Oauth2AuthorizationConsentRecord>?,
    parentPath: InverseForeignKey<out Record, Oauth2AuthorizationConsentRecord>?,
    aliased: Table<Oauth2AuthorizationConsentRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<Oauth2AuthorizationConsentRecord>(
    alias,
    Test.TEST,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of
         * <code>test.oauth2_authorization_consent</code>
         */
        val Oauth2AuthorizationConsentTable: Oauth2AuthorizationConsentTable = Oauth2AuthorizationConsentTable()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<Oauth2AuthorizationConsentRecord> = Oauth2AuthorizationConsentRecord::class.java

    /**
     * The column
     * <code>test.oauth2_authorization_consent.registered_client_id</code>.
     */
    val registeredClientId: TableField<Oauth2AuthorizationConsentRecord, String?> = createField(DSL.name("registered_client_id"), SQLDataType.VARCHAR(100).nullable(false), this, "")

    /**
     * The column <code>test.oauth2_authorization_consent.principal_name</code>.
     */
    val principalName: TableField<Oauth2AuthorizationConsentRecord, String?> = createField(DSL.name("principal_name"), SQLDataType.VARCHAR(200).nullable(false), this, "")

    /**
     * The column <code>test.oauth2_authorization_consent.authorities</code>.
     */
    val authorities: TableField<Oauth2AuthorizationConsentRecord, String?> = createField(DSL.name("authorities"), SQLDataType.VARCHAR(1000).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<Oauth2AuthorizationConsentRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<Oauth2AuthorizationConsentRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<Oauth2AuthorizationConsentRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>test.oauth2_authorization_consent</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>test.oauth2_authorization_consent</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>test.oauth2_authorization_consent</code> table reference
     */
    constructor(): this(DSL.name("oauth2_authorization_consent"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Test.TEST
    override fun getPrimaryKey(): UniqueKey<Oauth2AuthorizationConsentRecord> = KEY_OAUTH2_AUTHORIZATION_CONSENT_PRIMARY
    override fun `as`(alias: String): Oauth2AuthorizationConsentTable = Oauth2AuthorizationConsentTable(DSL.name(alias), this)
    override fun `as`(alias: Name): Oauth2AuthorizationConsentTable = Oauth2AuthorizationConsentTable(alias, this)
    override fun `as`(alias: Table<*>): Oauth2AuthorizationConsentTable = Oauth2AuthorizationConsentTable(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Oauth2AuthorizationConsentTable = Oauth2AuthorizationConsentTable(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Oauth2AuthorizationConsentTable = Oauth2AuthorizationConsentTable(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Oauth2AuthorizationConsentTable = Oauth2AuthorizationConsentTable(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Oauth2AuthorizationConsentTable = Oauth2AuthorizationConsentTable(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Oauth2AuthorizationConsentTable = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Oauth2AuthorizationConsentTable = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Oauth2AuthorizationConsentTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Oauth2AuthorizationConsentTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Oauth2AuthorizationConsentTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Oauth2AuthorizationConsentTable = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Oauth2AuthorizationConsentTable = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Oauth2AuthorizationConsentTable = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Oauth2AuthorizationConsentTable = where(DSL.notExists(select))
}
