/*
 * This file is generated by jOOQ.
 */
package org.railwaystations.rsapi.jooq.tables


import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.railwaystations.rsapi.jooq.Test
import org.railwaystations.rsapi.jooq.keys.FK_COUNTRY
import org.railwaystations.rsapi.jooq.keys.KEY_PROVIDERAPPS_PRIMARY
import org.railwaystations.rsapi.jooq.tables.CountriesTable.CountriesPath
import org.railwaystations.rsapi.jooq.tables.records.ProviderappsRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ProviderappsTable(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ProviderappsRecord>?,
    parentPath: InverseForeignKey<out Record, ProviderappsRecord>?,
    aliased: Table<ProviderappsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<ProviderappsRecord>(
    alias,
    Test.TEST,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>test.providerApps</code>
         */
        val ProviderappsTable: ProviderappsTable = ProviderappsTable()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ProviderappsRecord> = ProviderappsRecord::class.java

    /**
     * The column <code>test.providerApps.countryCode</code>.
     */
    val countrycode: TableField<ProviderappsRecord, String?> = createField(DSL.name("countryCode"), SQLDataType.CHAR(2).nullable(false), this, "")

    /**
     * The column <code>test.providerApps.type</code>.
     */
    val type: TableField<ProviderappsRecord, String?> = createField(DSL.name("type"), SQLDataType.VARCHAR(10).nullable(false), this, "")

    /**
     * The column <code>test.providerApps.name</code>.
     */
    val name: TableField<ProviderappsRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "")

    /**
     * The column <code>test.providerApps.url</code>.
     */
    val url: TableField<ProviderappsRecord, String?> = createField(DSL.name("url"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<ProviderappsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<ProviderappsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<ProviderappsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>test.providerApps</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>test.providerApps</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>test.providerApps</code> table reference
     */
    constructor(): this(DSL.name("providerApps"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ProviderappsRecord>?, parentPath: InverseForeignKey<out Record, ProviderappsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, ProviderappsTable, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class ProviderappsPath : ProviderappsTable, Path<ProviderappsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ProviderappsRecord>?, parentPath: InverseForeignKey<out Record, ProviderappsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<ProviderappsRecord>): super(alias, aliased)
        override fun `as`(alias: String): ProviderappsPath = ProviderappsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): ProviderappsPath = ProviderappsPath(alias, this)
        override fun `as`(alias: Table<*>): ProviderappsPath = ProviderappsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Test.TEST
    override fun getPrimaryKey(): UniqueKey<ProviderappsRecord> = KEY_PROVIDERAPPS_PRIMARY
    override fun getReferences(): List<ForeignKey<ProviderappsRecord, *>> = listOf(FK_COUNTRY)

    private lateinit var _countries: CountriesPath

    /**
     * Get the implicit join path to the <code>test.countries</code> table.
     */
    fun countries(): CountriesPath {
        if (!this::_countries.isInitialized)
            _countries = CountriesPath(this, FK_COUNTRY, null)

        return _countries;
    }

    val countries: CountriesPath
        get(): CountriesPath = countries()
    override fun `as`(alias: String): ProviderappsTable = ProviderappsTable(DSL.name(alias), this)
    override fun `as`(alias: Name): ProviderappsTable = ProviderappsTable(alias, this)
    override fun `as`(alias: Table<*>): ProviderappsTable = ProviderappsTable(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ProviderappsTable = ProviderappsTable(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ProviderappsTable = ProviderappsTable(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): ProviderappsTable = ProviderappsTable(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): ProviderappsTable = ProviderappsTable(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): ProviderappsTable = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): ProviderappsTable = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): ProviderappsTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): ProviderappsTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): ProviderappsTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): ProviderappsTable = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): ProviderappsTable = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): ProviderappsTable = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): ProviderappsTable = where(DSL.notExists(select))
}
