/*
 * This file is generated by jOOQ.
 */
package org.railwaystations.rsapi.jooq.tables


import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.railwaystations.rsapi.jooq.Test
import org.railwaystations.rsapi.jooq.keys.FK_PHOTO_STATION
import org.railwaystations.rsapi.jooq.keys.KEY_STATIONS_PRIMARY
import org.railwaystations.rsapi.jooq.tables.PhotosTable.PhotosPath
import org.railwaystations.rsapi.jooq.tables.records.StationsRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class StationsTable(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, StationsRecord>?,
    parentPath: InverseForeignKey<out Record, StationsRecord>?,
    aliased: Table<StationsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<StationsRecord>(
    alias,
    Test.TEST,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>test.stations</code>
         */
        val StationsTable: StationsTable = StationsTable()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<StationsRecord> = StationsRecord::class.java

    /**
     * The column <code>test.stations.countryCode</code>.
     */
    val countrycode: TableField<StationsRecord, String?> = createField(DSL.name("countryCode"), SQLDataType.CHAR(2).nullable(false), this, "")

    /**
     * The column <code>test.stations.id</code>.
     */
    val id: TableField<StationsRecord, String?> = createField(DSL.name("id"), SQLDataType.VARCHAR(30).nullable(false), this, "")

    /**
     * The column <code>test.stations.uicibnr</code>.
     */
    val uicibnr: TableField<StationsRecord, Int?> = createField(DSL.name("uicibnr"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "")

    /**
     * The column <code>test.stations.dbibnr</code>.
     */
    val dbibnr: TableField<StationsRecord, Int?> = createField(DSL.name("dbibnr"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "")

    /**
     * The column <code>test.stations.DS100</code>.
     */
    val ds100: TableField<StationsRecord, String?> = createField(DSL.name("DS100"), SQLDataType.VARCHAR(30).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>test.stations.title</code>.
     */
    val title: TableField<StationsRecord, String?> = createField(DSL.name("title"), SQLDataType.VARCHAR(100).nullable(false), this, "")

    /**
     * The column <code>test.stations.lat</code>.
     */
    val lat: TableField<StationsRecord, Double?> = createField(DSL.name("lat"), SQLDataType.DOUBLE.nullable(false), this, "")

    /**
     * The column <code>test.stations.lon</code>.
     */
    val lon: TableField<StationsRecord, Double?> = createField(DSL.name("lon"), SQLDataType.DOUBLE.nullable(false), this, "")

    /**
     * The column <code>test.stations.eva_id</code>.
     */
    val evaId: TableField<StationsRecord, Int?> = createField(DSL.name("eva_id"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "")

    /**
     * The column <code>test.stations.active</code>.
     */
    val active: TableField<StationsRecord, Boolean?> = createField(DSL.name("active"), SQLDataType.BIT.defaultValue(DSL.field(DSL.raw("b'1'"), SQLDataType.BIT)), this, "")

    private constructor(alias: Name, aliased: Table<StationsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<StationsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<StationsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>test.stations</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>test.stations</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>test.stations</code> table reference
     */
    constructor(): this(DSL.name("stations"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, StationsRecord>?, parentPath: InverseForeignKey<out Record, StationsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, StationsTable, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class StationsPath : StationsTable, Path<StationsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, StationsRecord>?, parentPath: InverseForeignKey<out Record, StationsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<StationsRecord>): super(alias, aliased)
        override fun `as`(alias: String): StationsPath = StationsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): StationsPath = StationsPath(alias, this)
        override fun `as`(alias: Table<*>): StationsPath = StationsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Test.TEST
    override fun getPrimaryKey(): UniqueKey<StationsRecord> = KEY_STATIONS_PRIMARY

    private lateinit var _photos: PhotosPath

    /**
     * Get the implicit to-many join path to the <code>test.photos</code> table
     */
    fun photos(): PhotosPath {
        if (!this::_photos.isInitialized)
            _photos = PhotosPath(this, null, FK_PHOTO_STATION.inverseKey)

        return _photos;
    }

    val photos: PhotosPath
        get(): PhotosPath = photos()
    override fun `as`(alias: String): StationsTable = StationsTable(DSL.name(alias), this)
    override fun `as`(alias: Name): StationsTable = StationsTable(alias, this)
    override fun `as`(alias: Table<*>): StationsTable = StationsTable(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): StationsTable = StationsTable(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): StationsTable = StationsTable(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): StationsTable = StationsTable(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): StationsTable = StationsTable(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): StationsTable = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): StationsTable = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): StationsTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): StationsTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): StationsTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): StationsTable = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): StationsTable = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): StationsTable = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): StationsTable = where(DSL.notExists(select))
}
