/*
 * This file is generated by jOOQ.
 */
package org.railwaystations.rsapi.jooq.tables


import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.railwaystations.rsapi.jooq.Test
import org.railwaystations.rsapi.jooq.keys.FK_INBOX_USER
import org.railwaystations.rsapi.jooq.keys.FK_PHOTO_USER
import org.railwaystations.rsapi.jooq.keys.KEY_USERS_EMAIL
import org.railwaystations.rsapi.jooq.keys.KEY_USERS_NAME
import org.railwaystations.rsapi.jooq.keys.KEY_USERS_PRIMARY
import org.railwaystations.rsapi.jooq.tables.InboxTable.InboxPath
import org.railwaystations.rsapi.jooq.tables.PhotosTable.PhotosPath
import org.railwaystations.rsapi.jooq.tables.records.UsersRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UsersTable(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, UsersRecord>?,
    parentPath: InverseForeignKey<out Record, UsersRecord>?,
    aliased: Table<UsersRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<UsersRecord>(
    alias,
    Test.TEST,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>test.users</code>
         */
        val UsersTable: UsersTable = UsersTable()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<UsersRecord> = UsersRecord::class.java

    /**
     * The column <code>test.users.id</code>.
     */
    val id: TableField<UsersRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>test.users.name</code>.
     */
    val name: TableField<UsersRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(50).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>test.users.email</code>.
     */
    val email: TableField<UsersRecord, String?> = createField(DSL.name("email"), SQLDataType.VARCHAR(100).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>test.users.url</code>.
     */
    val url: TableField<UsersRecord, String?> = createField(DSL.name("url"), SQLDataType.VARCHAR(1024).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>test.users.ownPhotos</code>.
     */
    val ownphotos: TableField<UsersRecord, Boolean?> = createField(DSL.name("ownPhotos"), SQLDataType.BIT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIT)), this, "")

    /**
     * The column <code>test.users.anonymous</code>.
     */
    val anonymous: TableField<UsersRecord, Boolean?> = createField(DSL.name("anonymous"), SQLDataType.BIT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIT)), this, "")

    /**
     * The column <code>test.users.license</code>.
     */
    val license: TableField<UsersRecord, String?> = createField(DSL.name("license"), SQLDataType.VARCHAR(50).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>test.users.key</code>.
     */
    val key: TableField<UsersRecord, String?> = createField(DSL.name("key"), SQLDataType.VARCHAR(1024).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>test.users.admin</code>.
     */
    val admin: TableField<UsersRecord, Boolean?> = createField(DSL.name("admin"), SQLDataType.BIT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIT)), this, "")

    /**
     * The column <code>test.users.emailVerification</code>.
     */
    val emailverification: TableField<UsersRecord, String?> = createField(DSL.name("emailVerification"), SQLDataType.VARCHAR(100).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>test.users.sendNotifications</code>.
     */
    val sendnotifications: TableField<UsersRecord, Boolean?> = createField(DSL.name("sendNotifications"), SQLDataType.BIT.defaultValue(DSL.field(DSL.raw("b'1'"), SQLDataType.BIT)), this, "")

    /**
     * The column <code>test.users.locale</code>.
     */
    val locale: TableField<UsersRecord, String?> = createField(DSL.name("locale"), SQLDataType.VARCHAR(20).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "")

    private constructor(alias: Name, aliased: Table<UsersRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<UsersRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<UsersRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>test.users</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>test.users</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>test.users</code> table reference
     */
    constructor(): this(DSL.name("users"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, UsersRecord>?, parentPath: InverseForeignKey<out Record, UsersRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, UsersTable, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class UsersPath : UsersTable, Path<UsersRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, UsersRecord>?, parentPath: InverseForeignKey<out Record, UsersRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<UsersRecord>): super(alias, aliased)
        override fun `as`(alias: String): UsersPath = UsersPath(DSL.name(alias), this)
        override fun `as`(alias: Name): UsersPath = UsersPath(alias, this)
        override fun `as`(alias: Table<*>): UsersPath = UsersPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Test.TEST
    override fun getIdentity(): Identity<UsersRecord, Int?> = super.getIdentity() as Identity<UsersRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<UsersRecord> = KEY_USERS_PRIMARY
    override fun getUniqueKeys(): List<UniqueKey<UsersRecord>> = listOf(KEY_USERS_EMAIL, KEY_USERS_NAME)

    private lateinit var _inbox: InboxPath

    /**
     * Get the implicit to-many join path to the <code>test.inbox</code> table
     */
    fun inbox(): InboxPath {
        if (!this::_inbox.isInitialized)
            _inbox = InboxPath(this, null, FK_INBOX_USER.inverseKey)

        return _inbox;
    }

    val inbox: InboxPath
        get(): InboxPath = inbox()

    private lateinit var _photos: PhotosPath

    /**
     * Get the implicit to-many join path to the <code>test.photos</code> table
     */
    fun photos(): PhotosPath {
        if (!this::_photos.isInitialized)
            _photos = PhotosPath(this, null, FK_PHOTO_USER.inverseKey)

        return _photos;
    }

    val photos: PhotosPath
        get(): PhotosPath = photos()
    override fun `as`(alias: String): UsersTable = UsersTable(DSL.name(alias), this)
    override fun `as`(alias: Name): UsersTable = UsersTable(alias, this)
    override fun `as`(alias: Table<*>): UsersTable = UsersTable(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): UsersTable = UsersTable(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): UsersTable = UsersTable(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): UsersTable = UsersTable(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): UsersTable = UsersTable(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): UsersTable = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): UsersTable = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): UsersTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): UsersTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): UsersTable = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): UsersTable = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): UsersTable = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): UsersTable = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): UsersTable = where(DSL.notExists(select))
}
