ALTER TABLE inbox ALTER COLUMN crc32 TYPE BIGINT USING crc32::bigint;

ALTER TABLE inbox ALTER COLUMN done SET NOT NULL;
ALTER TABLE inbox ALTER COLUMN done DROP DEFAULT;
ALTER TABLE inbox ALTER COLUMN notified SET NOT NULL;
ALTER TABLE inbox ALTER COLUMN notified DROP DEFAULT;
ALTER TABLE inbox ALTER COLUMN posted SET NOT NULL;
ALTER TABLE inbox ALTER COLUMN posted DROP DEFAULT;
ALTER TABLE inbox ALTER COLUMN createdat SET NOT NULL;
ALTER TABLE inbox ALTER COLUMN createdat DROP DEFAULT;
