loaderDe:
  bahnhoefeUrl: ${BAHNHOEFE_DE_URL:-http://94.136.168.53/bahnhoefe/_search?size=6000}
  photosUrl: ${PHOTOS_DE_URL:-https://railway-stations.org/bahnhoefe/de/bahnhofsfotos.json}
loaderCh:
  bahnhoefeUrl: ${BAHNHOEFE_CH_URL:-http://94.136.168.53/bahnhoefech/_search?size=6000}
  photosUrl: ${PHOTOS_CH_URL:-https://railway-stations.org/bahnhoefe/ch/bahnhofsfotos.json}
slackMonitorUrl: ${SLACK_MONITOR_URL:-}
