server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
      bindHost: 127.0.0.1
database:
  driverClass: org.mariadb.jdbc.Driver
  user: rsapi
  password: rsapi
  url: jdbc:mariadb://localhost:3306/rsapi
  properties:
    charSet: UTF-8
workDir: ${RSAPI_WORK:-/var/rsapi}
photoDir: ${PHOTO_DIR:-/tmp/railway-station-photos}
apiKey: ${API_KEY:-dummy}
salt: ${SALT:-dummy}
mailer:
  "@class": org.railwaystations.api.mail.SmtpMailer
  host: ${SMTP_HOST:-localhost}
  port: ${SMTP_PORT:-25}
  user: ${SMTP_USER:-}
  passwd: ${SMTP_PASSWD:-}
  from: ${SMTP_FROM:-}
slackMonitorUrl: ${SLACK_MONITOR_URL:-}
slackVerificationToken: ${SLACK_VERIFICATION_TOKEN:-dummy}
elasticBackend:
  baseUrl: ${ELASTIC_BASE_URL:-http://localhost:9200}
photographersUrl: fotografen
photoBaseUrl: https://fotos.railway-stations.org
