server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
      bindHost: 127.0.0.1
workDir: ${RSAPI_WORK:-/var/rsapi}
photoDir: ${PHOTO_DIR:-/tmp/railway-station-photos}
apiKey: ${API_KEY:-dummy}
salt: ${SALT:-dummy}
mailer:
  "@class": org.railwaystations.api.mail.SmtpMailer
  host: ${SMTP_HOST:-localhost}
  port: ${SMTP_PORT:-25}
  user: ${SMTP_USER:-}
  passwd: ${SMTP_PASSWD:-}
  from: ${SMTP_FROM:-}
slackMonitorUrl: ${SLACK_MONITOR_URL:-}
slackVerificationToken: ${SLACK_VERIFICATION_TOKEN:-dummy}
elasticBackend:
  baseUrl: ${ELASTIC_BASE_URL:-http://localhost:9200}
photographersUrl: /fotografen
photoBaseUrl: https://fotos.railway-stations.org
loaders:
  - type: deLoader
    country:
      code: de
      name: Deutschland
      timetableUrlTemplate: https://mobile.bahn.de/bin/mobil/bhftafel.exe/dox?bt=dep&max=10&rt=1&use_realtime_filter=1&start=yes&input={title}
    stationsUrl: /bahnhoefe
    photosUrl: /bahnhofsfotosde
  - type: baseLoader
    country:
      code: ch
      name: Schweiz
      email: "fotos@schweizer-bahnhoefe.ch"
      twitterTags: "@BahnhoefeCH, @android_oma, #BahnhofsfotoCH"
      timetableUrlTemplate: http://fahrplan.sbb.ch/bin/stboard.exe/dn?input={title}&REQTrain_name=&boardType=dep&time=now&maxJourneys=20&selectDate=today&productsFilter=1111111111&start=yes
    stationsUrl: /bahnhoefec2
    photosUrl: /bahnhofsfotosch
  - type: baseLoader
    country:
      code: fi
      name: Finnland
      timetableUrlTemplate: https://www.junat.net/en/
    stationsUrl: /bahnhoefefi
    photosUrl: /bahnhofsfotosfi
  - type: baseLoader
    country:
      code: uk
      name: United Kingdom
      timetableUrlTemplate: http://ojp.nationalrail.co.uk/service/ldbboard/dep/{DS100}
    stationsUrl: /bahnhoefeuk
    photosUrl: /bahnhofsfotosuk
  - type: baseLoader
    country:
      code: fr
      name: France
      timetableUrlTemplate: http://m.sncf.com/sncf/gare?libelleGare={title}
    stationsUrl: /bahnhoefefr
    photosUrl: /bahnhofsfotosfr
  - type: baseLoader
    country:
      code: es
      name: España
      timetableUrlTemplate: http://www.adif.es/AdifWeb/estacionesMapa.jsp?i=en_US&dest=&pes=informacion&e={DS100}
    stationsUrl: /bahnhoefees
    photosUrl: /bahnhofsfotoses
  - type: baseLoader
    country:
      code: pl
      name: Polska
      timetableUrlTemplate: http://mt.rozklad-pkp.pl/de/sq?input={id}&maxJourneys=15&start=start
    stationsUrl: /bahnhoefepl
    photosUrl: /bahnhofsfotospl
  - type: baseLoader
    country:
      code: nl
      name: Nederland
      timetableUrlTemplate: https://www.ns.nl/actuele-vertrektijden/avt?station={title}
    stationsUrl: /bahnhoefenl
    photosUrl: /bahnhofsfotosnl
  - type: baseLoader
    country:
      code: at
      name: Österreich
      timetableUrlTemplate: http://fahrplan.oebb.at/bin/stboard.exe/dn?L=vs_liveticker&evaId={id}&boardType=dep&productsFilter=1111111111111111&dirInput=&tickerID=dep&start=yes&eqstops=false&showJourneys=12&additionalTime=0
    stationsUrl: /bahnhoefeat
    photosUrl: /bahnhofsfotosat
  - type: baseLoader
    country:
      code: in
      name: India
      timetableUrlTemplate: https://enquiry.indianrail.gov.in/ntes/
    stationsUrl: /bahnhoefein
    photosUrl: /bahnhofsfotosin
  - type: baseLoader
    country:
      code: ie
      name: Ireland
      timetableUrlTemplate: http://www.irishrail.ie/timetables/live-departure-times?code={DS100}
    stationsUrl: /bahnhoefeie
    photosUrl: /bahnhofsfotosie
  - type: baseLoader
    country:
      code: "no"
      name: Norge
      timetableUrlTemplate: https://www.nsb.no/en/frontpage
    stationsUrl: /bahnhoefeno
    photosUrl: /bahnhofsfotosno
