server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
      bindHost: 127.0.0.1
workDir: ${UPLOAD_DIR:-/tmp/rsapi}
photoDir: ${PHOTO_DIR:-/tmp/railway-station-photos}
apiKey: ${API_KEY:-dummy}
salt: ${SALT:-dummy}
mailer:
  "@class": org.railwaystations.api.mail.SmtpMailer
  host: ${SMTP_HOST:-localhost}
  port: ${SMTP_PORT:-25}
  user: ${SMTP_USER:-}
  passwd: ${SMTP_PASSWD:-}
  from: ${SMTP_FROM:-}
photographersUrl: http://94.136.168.53/fotografen/_search?size=500
photoBaseUrl: https://fotos.railway-stations.org
loaders:
  - type: deLoader
    country:
      code: de
      name: Deutschland
      timetableUrlTemplate: https://mobile.bahn.de/bin/mobil/bhftafel.exe/dox?bt=dep&max=10&rt=1&use_realtime_filter=1&start=yes&input={title}
    stationsUrl: http://94.136.168.53/bahnhoefe/_search?size=7000
    photosUrl: http://94.136.168.53/bahnhofsfotosde/_search?size=7000
  - type: chLoader
    country:
      code: ch
      name: Schweiz
      email: "fotos@schweizer-bahnhoefe.ch"
      twitterTags: "@BahnhoefeCH, @android_oma, #BahnhofsfotoCH"
      timetableUrlTemplate: http://fahrplan.sbb.ch/bin/stboard.exe/dn?input={title}&REQTrain_name=&boardType=dep&time=now&maxJourneys=20&selectDate=today&productsFilter=1111111111&start=yes
    stationsUrl: http://94.136.168.53/bahnhoefech/_search?size=6000
    photosUrl: http://94.136.168.53/bahnhofsfotosch/_search?size=6000
  - type: baseLoader
    country:
      code: fi
      name: Finnland
      timetableUrlTemplate: https://www.junat.net/en/
    stationsUrl: http://94.136.168.53/bahnhoefefi/_search?size=500
    photosUrl: http://94.136.168.53/bahnhofsfotosfi/_search?size=500
  - type: baseLoader
    country:
      code: uk
      name: United Kingdom
      timetableUrlTemplate: http://ojp.nationalrail.co.uk/service/ldbboard/dep/{DS100}
    stationsUrl: http://94.136.168.53/bahnhoefeuk/_search?size=3000
    photosUrl: http://94.136.168.53/bahnhofsfotosuk/_search?size=3000
  - type: baseLoader
    country:
      code: fr
      name: France
      timetableUrlTemplate: http://m.sncf.com/sncf/gare?libelleGare={title}
    stationsUrl: http://94.136.168.53/bahnhoefefr/_search?size=5000
    photosUrl: http://94.136.168.53/bahnhofsfotosfr/_search?size=5000
  - type: baseLoader
    country:
      code: es
      name: España
      timetableUrlTemplate: http://www.adif.es/AdifWeb/estacionesMapa.jsp?i=en_US&dest=&pes=informacion&e={DS100}
    stationsUrl: http://94.136.168.53/bahnhoefees/_search?size=2000
    photosUrl: http://94.136.168.53/bahnhofsfotoses/_search?size=2000
  - type: baseLoader
    country:
      code: pl
      name: Polska
      timetableUrlTemplate: http://mt.rozklad-pkp.pl/de/sq?input={id}&maxJourneys=15&start=start
    stationsUrl: http://94.136.168.53/bahnhoefepl/_search?size=5000
    photosUrl: http://94.136.168.53/bahnhofsfotospl/_search?size=5000
  - type: baseLoader
    country:
      code: nl
      name: Nederland
      timetableUrlTemplate: https://www.ns.nl/actuele-vertrektijden/avt?station={title}
    stationsUrl: http://94.136.168.53/bahnhoefenl/_search?size=500
    photosUrl: http://94.136.168.53/bahnhofsfotosnl/_search?size=500
slackMonitorUrl: ${SLACK_MONITOR_URL:-}
slackVerificationToken: ${SLACK_VERIFICATION_TOKEN:-dummy}