---
version: '2.1'

services:

  mariadb:
    image: mariadb:11.6
    container_name: mariadb
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=rsapi
      - MARIADB_USER=rsapi
      - MARIADB_PASSWORD=rsapi
    network_mode: "host"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    labels:
      org.label-schema.group: "rsapi"
