---
version: '2.1'

services:

  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=rsapi
      - POSTGRES_USER=rsapi
      - POSTGRES_DB=rsapi
    network_mode: "host"
    labels:
      org.label-schema.group: "rsapi"
