---
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: rsapi
    password: rsapi
    url: jdbc:mariadb://localhost:3306/rsapi?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC&useLegacyDatetimeCode=false&sessionVariables=time_zone='+00:00'
  liquibase:
    change-log: classpath:migrations.xml
    contexts: test
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jackson:
    default-property-inclusion: non_null

server:
  error:
    include-message: NEVER
    include-stacktrace: NEVER
    whitelabel:
      enabled: true
  tomcat:
    max-swallow-size: 100MB

logging:
  level:
    root: DEBUG

management:
  server:
    port: 8081
    address: 127.0.0.1
  endpoints:
    web:
      exposure:
        include: "*"

# application
workDir: /var/rsapi
keepFileCopiesInDays: 60
photoBaseUrl: http://localhost:8080/photos
inboxBaseUrl: http://localhost:8080/inbox
mailVerificationUrl: http://localhost:8088/emailVerification.php?token=

# mailer
mailer:
  host:
  port:
  user:
  passwd:
  from: info@railway-stations.org

# Mastodon Bot
mastodon-bot:
  instanceUrl: https://botsin.space
  token:
  stationUrl: https://map.railway-stations.org/station.php

monitor:
  service: logging

# Matrix Monitor
matrix:
  uploadUrl: https://matrix.org/_matrix/media/r0/upload
  roomUrl:
  accessToken:
