---
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: rsapi
    password: rsapi
    url: jdbc:mariadb://localhost:3306/rsapi?useUnicode=yes&characterEncoding=UTF-8
  liquibase:
    change-log: classpath:migrations.xml
    contexts: test

server:
    error:
      whitelabel:
        enabled: false

logging:
  level:
    root: DEBUG

# application
workDir: /var/rsapi
salt: dummy
photoBaseUrl: http://localhost:8080/photos
inboxBaseUrl: http://localhost:8080/inbox
mailVerificationUrl: http://localhost:8088/emailVerification.php?token=

# mailer
mailer:
  host:
  port:
  user:
  passwd:
  from:


# Mastodon Bot
mastodonBot:
  instanceUrl: https://botsin.space
  token:
  stationUrl: https://map.railway-stations.org/station.php

# Matrix Monitor
matrix:
  uploadUrl: https://matrix.org/_matrix/media/r0/upload
  roomUrl:
  accessToken:
