/*
 * This file is generated by jOOQ.
 */
package org.railwaystations.rsapi.jooq.indexes


import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.railwaystations.rsapi.jooq.tables.InboxTable



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val INBOX_IDX_STATION: Index = Internal.createIndex(DSL.name("idx_station"), InboxTable.InboxTable, arrayOf(InboxTable.InboxTable.countrycode, InboxTable.InboxTable.stationid), false)
