/*
 * This file is generated by jOOQ.
 */
package org.railwaystations.rsapi.jooq.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Countries(
    val id: String,
    val name: String,
    val timetableurltemplate: String? = null,
    val email: String? = null,
    val overridelicense: String? = null,
    val active: Boolean? = null
): Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Countries = other as Countries
        if (this.id != o.id)
            return false
        if (this.name != o.name)
            return false
        if (this.timetableurltemplate == null) {
            if (o.timetableurltemplate != null)
                return false
        }
        else if (this.timetableurltemplate != o.timetableurltemplate)
            return false
        if (this.email == null) {
            if (o.email != null)
                return false
        }
        else if (this.email != o.email)
            return false
        if (this.overridelicense == null) {
            if (o.overridelicense != null)
                return false
        }
        else if (this.overridelicense != o.overridelicense)
            return false
        if (this.active == null) {
            if (o.active != null)
                return false
        }
        else if (this.active != o.active)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.id.hashCode()
        result = prime * result + this.name.hashCode()
        result = prime * result + (if (this.timetableurltemplate == null) 0 else this.timetableurltemplate.hashCode())
        result = prime * result + (if (this.email == null) 0 else this.email.hashCode())
        result = prime * result + (if (this.overridelicense == null) 0 else this.overridelicense.hashCode())
        result = prime * result + (if (this.active == null) 0 else this.active.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Countries (")

        sb.append(id)
        sb.append(", ").append(name)
        sb.append(", ").append(timetableurltemplate)
        sb.append(", ").append(email)
        sb.append(", ").append(overridelicense)
        sb.append(", ").append(active)

        sb.append(")")
        return sb.toString()
    }
}
