/*
 * This file is generated by jOOQ.
 */
package org.railwaystations.rsapi.jooq.tables.pojos


import java.io.Serializable
import java.time.Instant


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Oauth2Authorization(
    val id: String,
    val registeredClientId: String,
    val principalName: String,
    val authorizationGrantType: String,
    val authorizedScopes: String? = null,
    val attributes: String? = null,
    val state: String? = null,
    val authorizationCodeValue: String? = null,
    val authorizationCodeIssuedAt: Instant? = null,
    val authorizationCodeExpiresAt: Instant? = null,
    val authorizationCodeMetadata: String? = null,
    val accessTokenValue: String? = null,
    val accessTokenIssuedAt: Instant? = null,
    val accessTokenExpiresAt: Instant? = null,
    val accessTokenMetadata: String? = null,
    val accessTokenType: String? = null,
    val accessTokenScopes: String? = null,
    val oidcIdTokenValue: String? = null,
    val oidcIdTokenIssuedAt: Instant? = null,
    val oidcIdTokenExpiresAt: Instant? = null,
    val oidcIdTokenMetadata: String? = null,
    val refreshTokenValue: String? = null,
    val refreshTokenIssuedAt: Instant? = null,
    val refreshTokenExpiresAt: Instant? = null,
    val refreshTokenMetadata: String? = null,
    val userCodeValue: String? = null,
    val userCodeIssuedAt: Instant? = null,
    val userCodeExpiresAt: Instant? = null,
    val userCodeMetadata: String? = null,
    val deviceCodeValue: String? = null,
    val deviceCodeIssuedAt: Instant? = null,
    val deviceCodeExpiresAt: Instant? = null,
    val deviceCodeMetadata: String? = null
): Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Oauth2Authorization = other as Oauth2Authorization
        if (this.id != o.id)
            return false
        if (this.registeredClientId != o.registeredClientId)
            return false
        if (this.principalName != o.principalName)
            return false
        if (this.authorizationGrantType != o.authorizationGrantType)
            return false
        if (this.authorizedScopes == null) {
            if (o.authorizedScopes != null)
                return false
        }
        else if (this.authorizedScopes != o.authorizedScopes)
            return false
        if (this.attributes == null) {
            if (o.attributes != null)
                return false
        }
        else if (this.attributes != o.attributes)
            return false
        if (this.state == null) {
            if (o.state != null)
                return false
        }
        else if (this.state != o.state)
            return false
        if (this.authorizationCodeValue == null) {
            if (o.authorizationCodeValue != null)
                return false
        }
        else if (this.authorizationCodeValue != o.authorizationCodeValue)
            return false
        if (this.authorizationCodeIssuedAt == null) {
            if (o.authorizationCodeIssuedAt != null)
                return false
        }
        else if (this.authorizationCodeIssuedAt != o.authorizationCodeIssuedAt)
            return false
        if (this.authorizationCodeExpiresAt == null) {
            if (o.authorizationCodeExpiresAt != null)
                return false
        }
        else if (this.authorizationCodeExpiresAt != o.authorizationCodeExpiresAt)
            return false
        if (this.authorizationCodeMetadata == null) {
            if (o.authorizationCodeMetadata != null)
                return false
        }
        else if (this.authorizationCodeMetadata != o.authorizationCodeMetadata)
            return false
        if (this.accessTokenValue == null) {
            if (o.accessTokenValue != null)
                return false
        }
        else if (this.accessTokenValue != o.accessTokenValue)
            return false
        if (this.accessTokenIssuedAt == null) {
            if (o.accessTokenIssuedAt != null)
                return false
        }
        else if (this.accessTokenIssuedAt != o.accessTokenIssuedAt)
            return false
        if (this.accessTokenExpiresAt == null) {
            if (o.accessTokenExpiresAt != null)
                return false
        }
        else if (this.accessTokenExpiresAt != o.accessTokenExpiresAt)
            return false
        if (this.accessTokenMetadata == null) {
            if (o.accessTokenMetadata != null)
                return false
        }
        else if (this.accessTokenMetadata != o.accessTokenMetadata)
            return false
        if (this.accessTokenType == null) {
            if (o.accessTokenType != null)
                return false
        }
        else if (this.accessTokenType != o.accessTokenType)
            return false
        if (this.accessTokenScopes == null) {
            if (o.accessTokenScopes != null)
                return false
        }
        else if (this.accessTokenScopes != o.accessTokenScopes)
            return false
        if (this.oidcIdTokenValue == null) {
            if (o.oidcIdTokenValue != null)
                return false
        }
        else if (this.oidcIdTokenValue != o.oidcIdTokenValue)
            return false
        if (this.oidcIdTokenIssuedAt == null) {
            if (o.oidcIdTokenIssuedAt != null)
                return false
        }
        else if (this.oidcIdTokenIssuedAt != o.oidcIdTokenIssuedAt)
            return false
        if (this.oidcIdTokenExpiresAt == null) {
            if (o.oidcIdTokenExpiresAt != null)
                return false
        }
        else if (this.oidcIdTokenExpiresAt != o.oidcIdTokenExpiresAt)
            return false
        if (this.oidcIdTokenMetadata == null) {
            if (o.oidcIdTokenMetadata != null)
                return false
        }
        else if (this.oidcIdTokenMetadata != o.oidcIdTokenMetadata)
            return false
        if (this.refreshTokenValue == null) {
            if (o.refreshTokenValue != null)
                return false
        }
        else if (this.refreshTokenValue != o.refreshTokenValue)
            return false
        if (this.refreshTokenIssuedAt == null) {
            if (o.refreshTokenIssuedAt != null)
                return false
        }
        else if (this.refreshTokenIssuedAt != o.refreshTokenIssuedAt)
            return false
        if (this.refreshTokenExpiresAt == null) {
            if (o.refreshTokenExpiresAt != null)
                return false
        }
        else if (this.refreshTokenExpiresAt != o.refreshTokenExpiresAt)
            return false
        if (this.refreshTokenMetadata == null) {
            if (o.refreshTokenMetadata != null)
                return false
        }
        else if (this.refreshTokenMetadata != o.refreshTokenMetadata)
            return false
        if (this.userCodeValue == null) {
            if (o.userCodeValue != null)
                return false
        }
        else if (this.userCodeValue != o.userCodeValue)
            return false
        if (this.userCodeIssuedAt == null) {
            if (o.userCodeIssuedAt != null)
                return false
        }
        else if (this.userCodeIssuedAt != o.userCodeIssuedAt)
            return false
        if (this.userCodeExpiresAt == null) {
            if (o.userCodeExpiresAt != null)
                return false
        }
        else if (this.userCodeExpiresAt != o.userCodeExpiresAt)
            return false
        if (this.userCodeMetadata == null) {
            if (o.userCodeMetadata != null)
                return false
        }
        else if (this.userCodeMetadata != o.userCodeMetadata)
            return false
        if (this.deviceCodeValue == null) {
            if (o.deviceCodeValue != null)
                return false
        }
        else if (this.deviceCodeValue != o.deviceCodeValue)
            return false
        if (this.deviceCodeIssuedAt == null) {
            if (o.deviceCodeIssuedAt != null)
                return false
        }
        else if (this.deviceCodeIssuedAt != o.deviceCodeIssuedAt)
            return false
        if (this.deviceCodeExpiresAt == null) {
            if (o.deviceCodeExpiresAt != null)
                return false
        }
        else if (this.deviceCodeExpiresAt != o.deviceCodeExpiresAt)
            return false
        if (this.deviceCodeMetadata == null) {
            if (o.deviceCodeMetadata != null)
                return false
        }
        else if (this.deviceCodeMetadata != o.deviceCodeMetadata)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.id.hashCode()
        result = prime * result + this.registeredClientId.hashCode()
        result = prime * result + this.principalName.hashCode()
        result = prime * result + this.authorizationGrantType.hashCode()
        result = prime * result + (if (this.authorizedScopes == null) 0 else this.authorizedScopes.hashCode())
        result = prime * result + (if (this.attributes == null) 0 else this.attributes.hashCode())
        result = prime * result + (if (this.state == null) 0 else this.state.hashCode())
        result = prime * result + (if (this.authorizationCodeValue == null) 0 else this.authorizationCodeValue.hashCode())
        result = prime * result + (if (this.authorizationCodeIssuedAt == null) 0 else this.authorizationCodeIssuedAt.hashCode())
        result = prime * result + (if (this.authorizationCodeExpiresAt == null) 0 else this.authorizationCodeExpiresAt.hashCode())
        result = prime * result + (if (this.authorizationCodeMetadata == null) 0 else this.authorizationCodeMetadata.hashCode())
        result = prime * result + (if (this.accessTokenValue == null) 0 else this.accessTokenValue.hashCode())
        result = prime * result + (if (this.accessTokenIssuedAt == null) 0 else this.accessTokenIssuedAt.hashCode())
        result = prime * result + (if (this.accessTokenExpiresAt == null) 0 else this.accessTokenExpiresAt.hashCode())
        result = prime * result + (if (this.accessTokenMetadata == null) 0 else this.accessTokenMetadata.hashCode())
        result = prime * result + (if (this.accessTokenType == null) 0 else this.accessTokenType.hashCode())
        result = prime * result + (if (this.accessTokenScopes == null) 0 else this.accessTokenScopes.hashCode())
        result = prime * result + (if (this.oidcIdTokenValue == null) 0 else this.oidcIdTokenValue.hashCode())
        result = prime * result + (if (this.oidcIdTokenIssuedAt == null) 0 else this.oidcIdTokenIssuedAt.hashCode())
        result = prime * result + (if (this.oidcIdTokenExpiresAt == null) 0 else this.oidcIdTokenExpiresAt.hashCode())
        result = prime * result + (if (this.oidcIdTokenMetadata == null) 0 else this.oidcIdTokenMetadata.hashCode())
        result = prime * result + (if (this.refreshTokenValue == null) 0 else this.refreshTokenValue.hashCode())
        result = prime * result + (if (this.refreshTokenIssuedAt == null) 0 else this.refreshTokenIssuedAt.hashCode())
        result = prime * result + (if (this.refreshTokenExpiresAt == null) 0 else this.refreshTokenExpiresAt.hashCode())
        result = prime * result + (if (this.refreshTokenMetadata == null) 0 else this.refreshTokenMetadata.hashCode())
        result = prime * result + (if (this.userCodeValue == null) 0 else this.userCodeValue.hashCode())
        result = prime * result + (if (this.userCodeIssuedAt == null) 0 else this.userCodeIssuedAt.hashCode())
        result = prime * result + (if (this.userCodeExpiresAt == null) 0 else this.userCodeExpiresAt.hashCode())
        result = prime * result + (if (this.userCodeMetadata == null) 0 else this.userCodeMetadata.hashCode())
        result = prime * result + (if (this.deviceCodeValue == null) 0 else this.deviceCodeValue.hashCode())
        result = prime * result + (if (this.deviceCodeIssuedAt == null) 0 else this.deviceCodeIssuedAt.hashCode())
        result = prime * result + (if (this.deviceCodeExpiresAt == null) 0 else this.deviceCodeExpiresAt.hashCode())
        result = prime * result + (if (this.deviceCodeMetadata == null) 0 else this.deviceCodeMetadata.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Oauth2Authorization (")

        sb.append(id)
        sb.append(", ").append(registeredClientId)
        sb.append(", ").append(principalName)
        sb.append(", ").append(authorizationGrantType)
        sb.append(", ").append(authorizedScopes)
        sb.append(", ").append(attributes)
        sb.append(", ").append(state)
        sb.append(", ").append(authorizationCodeValue)
        sb.append(", ").append(authorizationCodeIssuedAt)
        sb.append(", ").append(authorizationCodeExpiresAt)
        sb.append(", ").append(authorizationCodeMetadata)
        sb.append(", ").append(accessTokenValue)
        sb.append(", ").append(accessTokenIssuedAt)
        sb.append(", ").append(accessTokenExpiresAt)
        sb.append(", ").append(accessTokenMetadata)
        sb.append(", ").append(accessTokenType)
        sb.append(", ").append(accessTokenScopes)
        sb.append(", ").append(oidcIdTokenValue)
        sb.append(", ").append(oidcIdTokenIssuedAt)
        sb.append(", ").append(oidcIdTokenExpiresAt)
        sb.append(", ").append(oidcIdTokenMetadata)
        sb.append(", ").append(refreshTokenValue)
        sb.append(", ").append(refreshTokenIssuedAt)
        sb.append(", ").append(refreshTokenExpiresAt)
        sb.append(", ").append(refreshTokenMetadata)
        sb.append(", ").append(userCodeValue)
        sb.append(", ").append(userCodeIssuedAt)
        sb.append(", ").append(userCodeExpiresAt)
        sb.append(", ").append(userCodeMetadata)
        sb.append(", ").append(deviceCodeValue)
        sb.append(", ").append(deviceCodeIssuedAt)
        sb.append(", ").append(deviceCodeExpiresAt)
        sb.append(", ").append(deviceCodeMetadata)

        sb.append(")")
        return sb.toString()
    }
}
