/*
 * This file is generated by jOOQ.
 */
package org.railwaystations.rsapi.jooq.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Oauth2AuthorizationConsent(
    val registeredClientId: String,
    val principalName: String,
    val authorities: String
): Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Oauth2AuthorizationConsent = other as Oauth2AuthorizationConsent
        if (this.registeredClientId != o.registeredClientId)
            return false
        if (this.principalName != o.principalName)
            return false
        if (this.authorities != o.authorities)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.registeredClientId.hashCode()
        result = prime * result + this.principalName.hashCode()
        result = prime * result + this.authorities.hashCode()
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Oauth2AuthorizationConsent (")

        sb.append(registeredClientId)
        sb.append(", ").append(principalName)
        sb.append(", ").append(authorities)

        sb.append(")")
        return sb.toString()
    }
}
