/*
 * This file is generated by jOOQ.
 */
package org.railwaystations.rsapi.jooq.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Providerapps(
    val countrycode: String,
    val type: String,
    val name: String,
    val url: String
): Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Providerapps = other as Providerapps
        if (this.countrycode != o.countrycode)
            return false
        if (this.type != o.type)
            return false
        if (this.name != o.name)
            return false
        if (this.url != o.url)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.countrycode.hashCode()
        result = prime * result + this.type.hashCode()
        result = prime * result + this.name.hashCode()
        result = prime * result + this.url.hashCode()
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Providerapps (")

        sb.append(countrycode)
        sb.append(", ").append(type)
        sb.append(", ").append(name)
        sb.append(", ").append(url)

        sb.append(")")
        return sb.toString()
    }
}
