/*
 * This file is generated by jOOQ.
 */
package org.railwaystations.rsapi.jooq.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Stations(
    val countrycode: String,
    val id: String,
    val uicibnr: Int? = null,
    val dbibnr: Int? = null,
    val ds100: String? = null,
    val title: String,
    val lat: Double,
    val lon: Double,
    val evaId: Int? = null,
    val active: Boolean? = null
): Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Stations = other as Stations
        if (this.countrycode != o.countrycode)
            return false
        if (this.id != o.id)
            return false
        if (this.uicibnr == null) {
            if (o.uicibnr != null)
                return false
        }
        else if (this.uicibnr != o.uicibnr)
            return false
        if (this.dbibnr == null) {
            if (o.dbibnr != null)
                return false
        }
        else if (this.dbibnr != o.dbibnr)
            return false
        if (this.ds100 == null) {
            if (o.ds100 != null)
                return false
        }
        else if (this.ds100 != o.ds100)
            return false
        if (this.title != o.title)
            return false
        if (this.lat != o.lat)
            return false
        if (this.lon != o.lon)
            return false
        if (this.evaId == null) {
            if (o.evaId != null)
                return false
        }
        else if (this.evaId != o.evaId)
            return false
        if (this.active == null) {
            if (o.active != null)
                return false
        }
        else if (this.active != o.active)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + this.countrycode.hashCode()
        result = prime * result + this.id.hashCode()
        result = prime * result + (if (this.uicibnr == null) 0 else this.uicibnr.hashCode())
        result = prime * result + (if (this.dbibnr == null) 0 else this.dbibnr.hashCode())
        result = prime * result + (if (this.ds100 == null) 0 else this.ds100.hashCode())
        result = prime * result + this.title.hashCode()
        result = prime * result + this.lat.hashCode()
        result = prime * result + this.lon.hashCode()
        result = prime * result + (if (this.evaId == null) 0 else this.evaId.hashCode())
        result = prime * result + (if (this.active == null) 0 else this.active.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Stations (")

        sb.append(countrycode)
        sb.append(", ").append(id)
        sb.append(", ").append(uicibnr)
        sb.append(", ").append(dbibnr)
        sb.append(", ").append(ds100)
        sb.append(", ").append(title)
        sb.append(", ").append(lat)
        sb.append(", ").append(lon)
        sb.append(", ").append(evaId)
        sb.append(", ").append(active)

        sb.append(")")
        return sb.toString()
    }
}
