/*
 * This file is generated by jOOQ.
 */
package org.railwaystations.rsapi.jooq.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Users(
    val id: Int? = null,
    val name: String? = null,
    val email: String? = null,
    val url: String? = null,
    val ownphotos: Boolean? = null,
    val anonymous: Boolean? = null,
    val license: String? = null,
    val key: String? = null,
    val admin: Boolean? = null,
    val emailverification: String? = null,
    val sendnotifications: Boolean? = null,
    val locale: String? = null
): Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Users = other as Users
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.name == null) {
            if (o.name != null)
                return false
        }
        else if (this.name != o.name)
            return false
        if (this.email == null) {
            if (o.email != null)
                return false
        }
        else if (this.email != o.email)
            return false
        if (this.url == null) {
            if (o.url != null)
                return false
        }
        else if (this.url != o.url)
            return false
        if (this.ownphotos == null) {
            if (o.ownphotos != null)
                return false
        }
        else if (this.ownphotos != o.ownphotos)
            return false
        if (this.anonymous == null) {
            if (o.anonymous != null)
                return false
        }
        else if (this.anonymous != o.anonymous)
            return false
        if (this.license == null) {
            if (o.license != null)
                return false
        }
        else if (this.license != o.license)
            return false
        if (this.key == null) {
            if (o.key != null)
                return false
        }
        else if (this.key != o.key)
            return false
        if (this.admin == null) {
            if (o.admin != null)
                return false
        }
        else if (this.admin != o.admin)
            return false
        if (this.emailverification == null) {
            if (o.emailverification != null)
                return false
        }
        else if (this.emailverification != o.emailverification)
            return false
        if (this.sendnotifications == null) {
            if (o.sendnotifications != null)
                return false
        }
        else if (this.sendnotifications != o.sendnotifications)
            return false
        if (this.locale == null) {
            if (o.locale != null)
                return false
        }
        else if (this.locale != o.locale)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + (if (this.name == null) 0 else this.name.hashCode())
        result = prime * result + (if (this.email == null) 0 else this.email.hashCode())
        result = prime * result + (if (this.url == null) 0 else this.url.hashCode())
        result = prime * result + (if (this.ownphotos == null) 0 else this.ownphotos.hashCode())
        result = prime * result + (if (this.anonymous == null) 0 else this.anonymous.hashCode())
        result = prime * result + (if (this.license == null) 0 else this.license.hashCode())
        result = prime * result + (if (this.key == null) 0 else this.key.hashCode())
        result = prime * result + (if (this.admin == null) 0 else this.admin.hashCode())
        result = prime * result + (if (this.emailverification == null) 0 else this.emailverification.hashCode())
        result = prime * result + (if (this.sendnotifications == null) 0 else this.sendnotifications.hashCode())
        result = prime * result + (if (this.locale == null) 0 else this.locale.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Users (")

        sb.append(id)
        sb.append(", ").append(name)
        sb.append(", ").append(email)
        sb.append(", ").append(url)
        sb.append(", ").append(ownphotos)
        sb.append(", ").append(anonymous)
        sb.append(", ").append(license)
        sb.append(", ").append(key)
        sb.append(", ").append(admin)
        sb.append(", ").append(emailverification)
        sb.append(", ").append(sendnotifications)
        sb.append(", ").append(locale)

        sb.append(")")
        return sb.toString()
    }
}
