/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.railwaystations.rsapi.adapter.web.controller

import jakarta.validation.Valid
import org.railwaystations.openapi.api.CountriesApiDelegate
import org.railwaystations.openapi.model.CountryDto
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestMethod
import org.springframework.web.bind.annotation.RequestParam

@Validated
interface CountriesApi2 {

    fun getDelegate(): CountriesApiDelegate = object : CountriesApiDelegate {}


    @RequestMapping(
        method = [RequestMethod.GET],
        value = ["/countries"],
        produces = ["application/json"]
    )
    fun getCountries(
        @Valid @RequestParam(
            value = "onlyActive",
            required = false
        ) onlyActive: Boolean?
    ): ResponseEntity<List<CountryDto>> {
        return getDelegate().getCountries(onlyActive)
    }
}
