/*
 * This file is generated by jOOQ.
 */
package org.railwaystations.rsapi.jooq.tables.records


import java.time.Instant

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import org.railwaystations.rsapi.jooq.tables.Oauth2AuthorizationTable
import org.railwaystations.rsapi.jooq.tables.pojos.Oauth2Authorization


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Oauth2AuthorizationRecord private constructor() : UpdatableRecordImpl<Oauth2AuthorizationRecord>(Oauth2AuthorizationTable.Oauth2AuthorizationTable) {

    open var id: String
        set(value): Unit = set(0, value)
        get(): String = get(0) as String

    open var registeredClientId: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    open var principalName: String
        set(value): Unit = set(2, value)
        get(): String = get(2) as String

    open var authorizationGrantType: String
        set(value): Unit = set(3, value)
        get(): String = get(3) as String

    open var authorizedScopes: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var attributes: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var state: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var authorizationCodeValue: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var authorizationCodeIssuedAt: Instant?
        set(value): Unit = set(8, value)
        get(): Instant? = get(8) as Instant?

    open var authorizationCodeExpiresAt: Instant?
        set(value): Unit = set(9, value)
        get(): Instant? = get(9) as Instant?

    open var authorizationCodeMetadata: String?
        set(value): Unit = set(10, value)
        get(): String? = get(10) as String?

    open var accessTokenValue: String?
        set(value): Unit = set(11, value)
        get(): String? = get(11) as String?

    open var accessTokenIssuedAt: Instant?
        set(value): Unit = set(12, value)
        get(): Instant? = get(12) as Instant?

    open var accessTokenExpiresAt: Instant?
        set(value): Unit = set(13, value)
        get(): Instant? = get(13) as Instant?

    open var accessTokenMetadata: String?
        set(value): Unit = set(14, value)
        get(): String? = get(14) as String?

    open var accessTokenType: String?
        set(value): Unit = set(15, value)
        get(): String? = get(15) as String?

    open var accessTokenScopes: String?
        set(value): Unit = set(16, value)
        get(): String? = get(16) as String?

    open var oidcIdTokenValue: String?
        set(value): Unit = set(17, value)
        get(): String? = get(17) as String?

    open var oidcIdTokenIssuedAt: Instant?
        set(value): Unit = set(18, value)
        get(): Instant? = get(18) as Instant?

    open var oidcIdTokenExpiresAt: Instant?
        set(value): Unit = set(19, value)
        get(): Instant? = get(19) as Instant?

    open var oidcIdTokenMetadata: String?
        set(value): Unit = set(20, value)
        get(): String? = get(20) as String?

    open var refreshTokenValue: String?
        set(value): Unit = set(21, value)
        get(): String? = get(21) as String?

    open var refreshTokenIssuedAt: Instant?
        set(value): Unit = set(22, value)
        get(): Instant? = get(22) as Instant?

    open var refreshTokenExpiresAt: Instant?
        set(value): Unit = set(23, value)
        get(): Instant? = get(23) as Instant?

    open var refreshTokenMetadata: String?
        set(value): Unit = set(24, value)
        get(): String? = get(24) as String?

    open var userCodeValue: String?
        set(value): Unit = set(25, value)
        get(): String? = get(25) as String?

    open var userCodeIssuedAt: Instant?
        set(value): Unit = set(26, value)
        get(): Instant? = get(26) as Instant?

    open var userCodeExpiresAt: Instant?
        set(value): Unit = set(27, value)
        get(): Instant? = get(27) as Instant?

    open var userCodeMetadata: String?
        set(value): Unit = set(28, value)
        get(): String? = get(28) as String?

    open var deviceCodeValue: String?
        set(value): Unit = set(29, value)
        get(): String? = get(29) as String?

    open var deviceCodeIssuedAt: Instant?
        set(value): Unit = set(30, value)
        get(): Instant? = get(30) as Instant?

    open var deviceCodeExpiresAt: Instant?
        set(value): Unit = set(31, value)
        get(): Instant? = get(31) as Instant?

    open var deviceCodeMetadata: String?
        set(value): Unit = set(32, value)
        get(): String? = get(32) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised Oauth2AuthorizationRecord
     */
    constructor(id: String, registeredClientId: String, principalName: String, authorizationGrantType: String, authorizedScopes: String? = null, attributes: String? = null, state: String? = null, authorizationCodeValue: String? = null, authorizationCodeIssuedAt: Instant? = null, authorizationCodeExpiresAt: Instant? = null, authorizationCodeMetadata: String? = null, accessTokenValue: String? = null, accessTokenIssuedAt: Instant? = null, accessTokenExpiresAt: Instant? = null, accessTokenMetadata: String? = null, accessTokenType: String? = null, accessTokenScopes: String? = null, oidcIdTokenValue: String? = null, oidcIdTokenIssuedAt: Instant? = null, oidcIdTokenExpiresAt: Instant? = null, oidcIdTokenMetadata: String? = null, refreshTokenValue: String? = null, refreshTokenIssuedAt: Instant? = null, refreshTokenExpiresAt: Instant? = null, refreshTokenMetadata: String? = null, userCodeValue: String? = null, userCodeIssuedAt: Instant? = null, userCodeExpiresAt: Instant? = null, userCodeMetadata: String? = null, deviceCodeValue: String? = null, deviceCodeIssuedAt: Instant? = null, deviceCodeExpiresAt: Instant? = null, deviceCodeMetadata: String? = null): this() {
        this.id = id
        this.registeredClientId = registeredClientId
        this.principalName = principalName
        this.authorizationGrantType = authorizationGrantType
        this.authorizedScopes = authorizedScopes
        this.attributes = attributes
        this.state = state
        this.authorizationCodeValue = authorizationCodeValue
        this.authorizationCodeIssuedAt = authorizationCodeIssuedAt
        this.authorizationCodeExpiresAt = authorizationCodeExpiresAt
        this.authorizationCodeMetadata = authorizationCodeMetadata
        this.accessTokenValue = accessTokenValue
        this.accessTokenIssuedAt = accessTokenIssuedAt
        this.accessTokenExpiresAt = accessTokenExpiresAt
        this.accessTokenMetadata = accessTokenMetadata
        this.accessTokenType = accessTokenType
        this.accessTokenScopes = accessTokenScopes
        this.oidcIdTokenValue = oidcIdTokenValue
        this.oidcIdTokenIssuedAt = oidcIdTokenIssuedAt
        this.oidcIdTokenExpiresAt = oidcIdTokenExpiresAt
        this.oidcIdTokenMetadata = oidcIdTokenMetadata
        this.refreshTokenValue = refreshTokenValue
        this.refreshTokenIssuedAt = refreshTokenIssuedAt
        this.refreshTokenExpiresAt = refreshTokenExpiresAt
        this.refreshTokenMetadata = refreshTokenMetadata
        this.userCodeValue = userCodeValue
        this.userCodeIssuedAt = userCodeIssuedAt
        this.userCodeExpiresAt = userCodeExpiresAt
        this.userCodeMetadata = userCodeMetadata
        this.deviceCodeValue = deviceCodeValue
        this.deviceCodeIssuedAt = deviceCodeIssuedAt
        this.deviceCodeExpiresAt = deviceCodeExpiresAt
        this.deviceCodeMetadata = deviceCodeMetadata
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised Oauth2AuthorizationRecord
     */
    constructor(value: Oauth2Authorization?): this() {
        if (value != null) {
            this.id = value.id
            this.registeredClientId = value.registeredClientId
            this.principalName = value.principalName
            this.authorizationGrantType = value.authorizationGrantType
            this.authorizedScopes = value.authorizedScopes
            this.attributes = value.attributes
            this.state = value.state
            this.authorizationCodeValue = value.authorizationCodeValue
            this.authorizationCodeIssuedAt = value.authorizationCodeIssuedAt
            this.authorizationCodeExpiresAt = value.authorizationCodeExpiresAt
            this.authorizationCodeMetadata = value.authorizationCodeMetadata
            this.accessTokenValue = value.accessTokenValue
            this.accessTokenIssuedAt = value.accessTokenIssuedAt
            this.accessTokenExpiresAt = value.accessTokenExpiresAt
            this.accessTokenMetadata = value.accessTokenMetadata
            this.accessTokenType = value.accessTokenType
            this.accessTokenScopes = value.accessTokenScopes
            this.oidcIdTokenValue = value.oidcIdTokenValue
            this.oidcIdTokenIssuedAt = value.oidcIdTokenIssuedAt
            this.oidcIdTokenExpiresAt = value.oidcIdTokenExpiresAt
            this.oidcIdTokenMetadata = value.oidcIdTokenMetadata
            this.refreshTokenValue = value.refreshTokenValue
            this.refreshTokenIssuedAt = value.refreshTokenIssuedAt
            this.refreshTokenExpiresAt = value.refreshTokenExpiresAt
            this.refreshTokenMetadata = value.refreshTokenMetadata
            this.userCodeValue = value.userCodeValue
            this.userCodeIssuedAt = value.userCodeIssuedAt
            this.userCodeExpiresAt = value.userCodeExpiresAt
            this.userCodeMetadata = value.userCodeMetadata
            this.deviceCodeValue = value.deviceCodeValue
            this.deviceCodeIssuedAt = value.deviceCodeIssuedAt
            this.deviceCodeExpiresAt = value.deviceCodeExpiresAt
            this.deviceCodeMetadata = value.deviceCodeMetadata
            resetChangedOnNotNull()
        }
    }
}
