/*
 * This file is generated by jOOQ.
 */
package org.railwaystations.rsapi.jooq.tables.references


import org.railwaystations.rsapi.jooq.tables.BlockedUsernamesTable
import org.railwaystations.rsapi.jooq.tables.CountriesTable
import org.railwaystations.rsapi.jooq.tables.InboxTable
import org.railwaystations.rsapi.jooq.tables.Oauth2AuthorizationConsentTable
import org.railwaystations.rsapi.jooq.tables.Oauth2AuthorizationTable
import org.railwaystations.rsapi.jooq.tables.Oauth2RegisteredClientTable
import org.railwaystations.rsapi.jooq.tables.PhotosTable
import org.railwaystations.rsapi.jooq.tables.ProviderappsTable
import org.railwaystations.rsapi.jooq.tables.StationsTable
import org.railwaystations.rsapi.jooq.tables.UsersTable



/**
 * The table <code>test.blocked_usernames</code>.
 */
val BlockedUsernamesTable: BlockedUsernamesTable = org.railwaystations.rsapi.jooq.tables.BlockedUsernamesTable.BlockedUsernamesTable

/**
 * The table <code>test.countries</code>.
 */
val CountriesTable: CountriesTable = org.railwaystations.rsapi.jooq.tables.CountriesTable.CountriesTable

/**
 * The table <code>test.inbox</code>.
 */
val InboxTable: InboxTable = org.railwaystations.rsapi.jooq.tables.InboxTable.InboxTable

/**
 * The table <code>test.oauth2_authorization</code>.
 */
val Oauth2AuthorizationTable: Oauth2AuthorizationTable = org.railwaystations.rsapi.jooq.tables.Oauth2AuthorizationTable.Oauth2AuthorizationTable

/**
 * The table <code>test.oauth2_authorization_consent</code>.
 */
val Oauth2AuthorizationConsentTable: Oauth2AuthorizationConsentTable = org.railwaystations.rsapi.jooq.tables.Oauth2AuthorizationConsentTable.Oauth2AuthorizationConsentTable

/**
 * The table <code>test.oauth2_registered_client</code>.
 */
val Oauth2RegisteredClientTable: Oauth2RegisteredClientTable = org.railwaystations.rsapi.jooq.tables.Oauth2RegisteredClientTable.Oauth2RegisteredClientTable

/**
 * The table <code>test.photos</code>.
 */
val PhotosTable: PhotosTable = org.railwaystations.rsapi.jooq.tables.PhotosTable.PhotosTable

/**
 * The table <code>test.providerApps</code>.
 */
val ProviderappsTable: ProviderappsTable = org.railwaystations.rsapi.jooq.tables.ProviderappsTable.ProviderappsTable

/**
 * The table <code>test.stations</code>.
 */
val StationsTable: StationsTable = org.railwaystations.rsapi.jooq.tables.StationsTable.StationsTable

/**
 * The table <code>test.users</code>.
 */
val UsersTable: UsersTable = org.railwaystations.rsapi.jooq.tables.UsersTable.UsersTable
