/*
 * This file is generated by jOOQ.
 */
package org.railwaystations.rsapi.jooq


import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl
import org.railwaystations.rsapi.jooq.tables.BlockedUsernamesTable
import org.railwaystations.rsapi.jooq.tables.CountriesTable
import org.railwaystations.rsapi.jooq.tables.InboxTable
import org.railwaystations.rsapi.jooq.tables.Oauth2AuthorizationConsentTable
import org.railwaystations.rsapi.jooq.tables.Oauth2AuthorizationTable
import org.railwaystations.rsapi.jooq.tables.Oauth2RegisteredClientTable
import org.railwaystations.rsapi.jooq.tables.PhotosTable
import org.railwaystations.rsapi.jooq.tables.ProviderappsTable
import org.railwaystations.rsapi.jooq.tables.StationsTable
import org.railwaystations.rsapi.jooq.tables.UsersTable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Test : SchemaImpl("test", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>test</code>
         */
        val TEST: Test = Test()
    }

    /**
     * The table <code>test.blocked_usernames</code>.
     */
    val BlockedUsernamesTable: BlockedUsernamesTable get() = org.railwaystations.rsapi.jooq.tables.BlockedUsernamesTable.BlockedUsernamesTable

    /**
     * The table <code>test.countries</code>.
     */
    val CountriesTable: CountriesTable get() = org.railwaystations.rsapi.jooq.tables.CountriesTable.CountriesTable

    /**
     * The table <code>test.inbox</code>.
     */
    val InboxTable: InboxTable get() = org.railwaystations.rsapi.jooq.tables.InboxTable.InboxTable

    /**
     * The table <code>test.oauth2_authorization</code>.
     */
    val Oauth2AuthorizationTable: Oauth2AuthorizationTable get() = org.railwaystations.rsapi.jooq.tables.Oauth2AuthorizationTable.Oauth2AuthorizationTable

    /**
     * The table <code>test.oauth2_authorization_consent</code>.
     */
    val Oauth2AuthorizationConsentTable: Oauth2AuthorizationConsentTable get() = org.railwaystations.rsapi.jooq.tables.Oauth2AuthorizationConsentTable.Oauth2AuthorizationConsentTable

    /**
     * The table <code>test.oauth2_registered_client</code>.
     */
    val Oauth2RegisteredClientTable: Oauth2RegisteredClientTable get() = org.railwaystations.rsapi.jooq.tables.Oauth2RegisteredClientTable.Oauth2RegisteredClientTable

    /**
     * The table <code>test.photos</code>.
     */
    val PhotosTable: PhotosTable get() = org.railwaystations.rsapi.jooq.tables.PhotosTable.PhotosTable

    /**
     * The table <code>test.providerApps</code>.
     */
    val ProviderappsTable: ProviderappsTable get() = org.railwaystations.rsapi.jooq.tables.ProviderappsTable.ProviderappsTable

    /**
     * The table <code>test.stations</code>.
     */
    val StationsTable: StationsTable get() = org.railwaystations.rsapi.jooq.tables.StationsTable.StationsTable

    /**
     * The table <code>test.users</code>.
     */
    val UsersTable: UsersTable get() = org.railwaystations.rsapi.jooq.tables.UsersTable.UsersTable

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        org.railwaystations.rsapi.jooq.tables.BlockedUsernamesTable.BlockedUsernamesTable,
        org.railwaystations.rsapi.jooq.tables.CountriesTable.CountriesTable,
        org.railwaystations.rsapi.jooq.tables.InboxTable.InboxTable,
        org.railwaystations.rsapi.jooq.tables.Oauth2AuthorizationTable.Oauth2AuthorizationTable,
        org.railwaystations.rsapi.jooq.tables.Oauth2AuthorizationConsentTable.Oauth2AuthorizationConsentTable,
        org.railwaystations.rsapi.jooq.tables.Oauth2RegisteredClientTable.Oauth2RegisteredClientTable,
        org.railwaystations.rsapi.jooq.tables.PhotosTable.PhotosTable,
        org.railwaystations.rsapi.jooq.tables.ProviderappsTable.ProviderappsTable,
        org.railwaystations.rsapi.jooq.tables.StationsTable.StationsTable,
        org.railwaystations.rsapi.jooq.tables.UsersTable.UsersTable
    )
}
