name: Build and Test

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3.9.0
        with:
          java-version: '18'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@dabb1b52d35733fde278c288e4781d4336d4c29c
      - name: Build with Gradle
        run: ./gradlew --no-daemon build bootJar